### ISSUE TITLE
Cancelable send_with_timer

### ISSUE THREAD

**Issue by balliegojr** [lemunozm/message-io#114]
Hi, 

It would be very nice to have a way to cancel messages scheduled with `send_with_timer`.

I also have a question. I need to encrypt the network traffic, do you recommend implementing an adapter for this or just encrypt the content of the messages before sending them?

**Comment by lemunozm** [comment]
Hi @balliegojr, 

Yeah! it could be a great addition. I think it is easy,  later I will make a PR with this feature.

Regarding encryption, you can do it in both ways with its pros/cons:
- Choosing the content to encrypt is probably easier and you could encrypt any transport. But maybe, depending on your encryption, losing a UDP packet, for example, would imply that the receiver could no longer decrypt more messages. Also, some bytes could not be sent encrypted if the transport uses some internal header as `FramedTcp` that sends the size of the packet for each message.
- Choosing the adapter to encrypt inside of it, is probably harder to program but maybe for your needs, you have more control. Also, your encryption state can be easily stored along with the connection, making transparent its usage from the message-io API. (and ever you could do a PR in the future if you want to make public that adapter 😄 ).

**Comment by lemunozm** [comment]
Done in https://github.com/lemunozm/message-io/pull/115

**Comment by balliegojr** [comment]
Hi @lemunozm,

Wow, that was fast!.
Thank you very much

I will see what to do regarding the encryption thing... still not decided yet
